name: prototype_mb_solutions
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  english_words: ^4.0.0
  provider: ^6.0.0
  firebase_core: ^3.8.1
  google_sign_in: ^6.2.2
  firebase_auth: ^5.3.4
  flutter_dotenv: ^5.2.1

flutter:
  uses-material-design: true
